### ISSUE TITLE
Relay access denied

### ISSUE THREAD

**Issue by pecosus** [arlowhite/process-watcher#5]
Hi! Im trying to run the script but it return the following error:

Sending email to:  my_email@gmail.com
Exception encountered while checking or communicating about process 1829251
Traceback (most recent call last):
  File "/usr/serverbin/process_watcher", line 149, in <module>
    comm.send(process=process, subject_format=template, **send_args)
  File "/home/genoma/.installedsoftware/process-watcher/communicate/email.py", line 29, in send
    s.send_message(msg)
  File "/usr/lib/python3.7/smtplib.py", line 967, in send_message
    rcpt_options)
  File "/usr/lib/python3.7/smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'my_email@gmail.com': (554, b'5.7.1 <my_email@gmail.com>: Relay access denied')}

Its looks like a problem with a postfix configuration file, but I've tried everything.

May you help me?

Thanks!

**Comment by arlowhite** [comment]
Looks like it's an error outside of `process_watcher`

If it does require a code change to this project, create a Pull Request and I'll look at it.
